/*
 * Copyright (C) EdgeTX
 *
 * Based on code named
 *   opentx - https://github.com/opentx/opentx
 */

#include <string.h>

#include "stm32_hal_ll.h"
#include "stm32_gpio.h"

#include "hal/adc_driver.h"
#include "hal/trainer_driver.h"
#include "hal/switch_driver.h"
#include "hal/module_port.h"
#include "hal/abnormal_reboot.h"
#include "hal/usb_driver.h"
#include "hal/gpio.h"

#include "board.h"
#include "debug.h"
#include "rtc.h"
#include "fifo.h"

#include "io/crsf/crsf_utilities.h"
#include "io/crsf/crossfire.h"

#if !defined(BOOT)
  #include "edgetx.h"
  #include "crsf_tasks.h"
  #include "FreeRTOS.h"
  #include "task.h"
  #include "semphr.h"
  #include "queue.h"
#endif

#include "stm32_adc.h"

HardwareOptions hardwareOptions;

#if !defined(BOOT)
static uint32_t trampoline[TRAMPOLINE_INDEX_COUNT] = {0};
// _adc_driver is now generated by boards/generic_stm32/analog_inputs.cpp
// from radio/src/boards/hw_defs/tango.json (only VBAT is on the main
// MCU's ADC — sticks come from the CRSF blob via crossfireSharedData).
#include "boards/generic_stm32/analog_inputs.h"
#endif

#include "stm32_timer.h"

#if !defined(WAS_RESET_BY_WATCHDOG)
#define WAS_RESET_BY_WATCHDOG()             (RCC->CSR & (RCC_CSR_WDGRSTF | RCC_CSR_WWDGRSTF))
#endif

// Start TIMER at 2000000Hz
void init2MhzTimer()
{
  stm32_timer_enable_clock(TIMER_2MHz_TIMER);
  TIMER_2MHz_TIMER->PSC = (PERI1_FREQUENCY * TIMER_MULT_APB1) / 2000000 - 1; // 0.5 uS, 2 MHz
  TIMER_2MHz_TIMER->ARR = 65535;
  TIMER_2MHz_TIMER->CR2 = 0;
  TIMER_2MHz_TIMER->CR1 = TIM_CR1_CEN;
}

void watchdogInit(unsigned int duration)
{
  IWDG->KR = 0x5555;      // Unlock registers
  IWDG->PR = 3;           // Divide by 32 => 1kHz clock
  IWDG->KR = 0x5555;      // Unlock registers
  IWDG->RLR = duration;
  IWDG->KR = 0xAAAA;      // Start WDT
}

void watchdogReset()
{
  IWDG->KR = 0xAAAA;
}

void watchdogEnable(uint32_t duration)
{
  watchdogInit(duration);
}

#if defined(SPORT_UPDATE_PWR_GPIO)
void sportUpdatePowerOn()
{
  gpio_init(SPORT_UPDATE_PWR_GPIO, GPIO_OUT, GPIO_PIN_SPEED_LOW);
  gpio_set(SPORT_UPDATE_PWR_GPIO);
}

void sportUpdatePowerOff()
{
  gpio_clear(SPORT_UPDATE_PWR_GPIO);
}
#endif

typedef Fifo<uint8_t, 256> ModuleFifo;
ModuleFifo intmoduleFifo;

#if !defined(BOOT)
void INTERNAL_MODULE_OFF()
{
  crossfireTurnOffRf(false);
}

void INTERNAL_MODULE_ON()
{
  crossfireTurnOnRf();
}

bool IS_INTERNAL_MODULE_ON()
{
  return isCrossfireRfOn();
}

void intmoduleSendBuffer(unsigned char const*, unsigned char)
{
  // TODO
}
#endif

// RTC backup register layout on F413 (20 × 32-bit BKPxR words).
//   BKP0R, BKP1R : SET_POWER_REASON (value + POWER_REASON_SIGNATURE)
//   BKP2R..BKP12R: readBackupReg(index) / writeBackupReg(index, val),
//                  with index being the BKREG_INDEX enum from
//                  io/crsf/crossfire.h. (11 values, fits in 11 regs.)
// The legacy TBS firmware used BKPSRAM (4 KB, not present on F413) for the
// BKREG_* region and only BKP0R/BKP1R for the power-reason signature. The
// RTC backup registers survive reset AND power-off (backed by VBAT), which
// is the same persistence guarantee BKPSRAM had.
#define TBS_BKREG_OFFSET 2

static volatile uint32_t* tbs_bkp_reg(uint8_t index)
{
  // BKP0R..BKP19R are contiguous __IO uint32_t in the RTC_TypeDef struct;
  // index off the base to reach BKPxR[index + offset].
  return &(&RTC->BKP0R)[index + TBS_BKREG_OFFSET];
}

uint32_t readBackupReg(uint8_t index)
{
  return *tbs_bkp_reg(index);
}

void writeBackupReg(uint8_t index, uint32_t data)
{
  // Unlock backup-domain write access, then write. RCC/PWR clocks are
  // already on by boardInit(); we only need to set DBP.
  PWR->CR |= PWR_CR_DBP;
  *tbs_bkp_reg(index) = data;
}

void SET_POWER_REASON(uint32_t value)
{
  PWR->CR |= PWR_CR_DBP;
  RTC->BKP0R = value;
  RTC->BKP1R = POWER_REASON_SIGNATURE;
}

uint32_t bkregGetStatusFlag(uint32_t flag) {
  return readBackupReg(BKREG_STATUS_FLAG) & (1u << flag);
}

void bkregSetStatusFlag(uint32_t flag) {
  uint32_t v = readBackupReg(BKREG_STATUS_FLAG);
  writeBackupReg(BKREG_STATUS_FLAG, v | (1u << flag));
}

void bkregClrStatusFlag(uint32_t flag) {
  uint32_t v = readBackupReg(BKREG_STATUS_FLAG);
  writeBackupReg(BKREG_STATUS_FLAG, v & ~(1u << flag));
}

static uint8_t isDisableBoardOff() {
  return bkregGetStatusFlag(BKREG_SKIP_BOARD_OFF);
}

void runPwrOffCharging()
{
  uint32_t tmrAdc = g_tmr10ms;
  uint32_t tmrPressed = g_tmr10ms;

  while (1) {
    if (g_tmr10ms - tmrAdc >= 10) {
      // TODO(port Phase B): battery check during charging loop — was
      // checkBattery() in the legacy code; the modern entry point is in
      // edgetx.cpp and requires the main task to be running.
      tmrAdc = g_tmr10ms;
    }

    if (g_tmr10ms - tmrPressed >= 10) {
      if (pwrPressed()) {
        pwrOn();
        break;
      }
      tmrPressed = g_tmr10ms;
    }

#if !defined(BOOT)
    if (getCrsfFlag(CRSF_FLAG_CHARGING) && !getCrsfFlag(CRSF_FLAG_CHARGING_FAULT) && usbPlugged()) {
      // simplified charging logic
    }
#endif

    if (!usbPlugged()) {
      pwrOff();
    }
    
    watchdogReset();
  }
}

// Build-time expected DEV_ID for the chip CMakeLists.txt targets. These
// are the low 12 bits of DBGMCU->IDCODE (RM0430 / RM0090).
//   STM32F405/407/415/417 = 0x413   (MAMBO — F407xE, also early-rev TANGO)
//   STM32F413/423          = 0x463   (TANGO — F413xG, later rev)
// If the MCU on the actual device returns something else we refuse to
// init so the user doesn't run a build whose peripheral map doesn't
// match its silicon.
#if defined(STM32F413xx)
#define TBS_EXPECTED_DEV_ID  0x463U
#elif defined(STM32F407xx)
#define TBS_EXPECTED_DEV_ID  0x413U
#else
#error "TBS: no DEV_ID expectation for this chip; update board.cpp"
#endif

static void tbs_verify_cpu_or_halt()
{
  uint32_t idcode = DBGMCU->IDCODE;
  uint32_t dev_id = idcode & 0xFFFU;
  if (dev_id == TBS_EXPECTED_DEV_ID) {
    return; // match — all good
  }
  // Mismatch: refuse to latch power and spin. The user's press of the
  // power button is held through a soft-latch circuit on PWR_ON_GPIO;
  // by not calling pwrOn() we guarantee the radio drops power the
  // moment the button is released. Far less bad than booting on a
  // wrong-ID chip (wrong SRAM size, wrong peripheral map — likely
  // hard-faults somewhere subtle and leaves the blob region in an
  // undefined state on flash regions that DO line up).
  while (1) {
    /* wait for the user to release the power button — hardware drops
       our Vdd and we reset into the bootloader next plug-in */
  }
}

void boardInit()
{
  // First thing we do: check the chip matches our build. If not, refuse
  // to power-latch and spin. Peripheral accesses further down will
  // hard-fault on a wrong chip in ways that are much harder to diagnose.
  tbs_verify_cpu_or_halt();

  bool skipCharging = false;

  pwrInit();
  pwrOn();
  keysInit();

#if defined(ROTARY_ENCODER_NAVIGATION)
  rotaryEncoderInit();
#endif
  delaysInit();

#if !defined(BOOT)
  if (!adcInit(&_adc_driver))
    TRACE("adcInit failed");
#endif

#if defined(RADIO_MAMBO)
  backlightInit();
#if !defined(BOOT)
  // BACKLIGHT_ENABLE expands to backlightEnable(g_eeGeneral.backlightBright),
  // and g_eeGeneral doesn't exist in the bootloader build. Call the raw
  // max-brightness path instead so the bootloader's splash screen is
  // readable.
  BACKLIGHT_ENABLE();
#else
  backlightEnable(BACKLIGHT_LEVEL_MAX);
#endif
#endif
  lcdInit(); 
  audioInit();
  init2MhzTimer();
  timersInit();
#if !defined(BOOT)
  crsfInit();
#endif
  usbInit();
#if defined(CHARGING_LEDS)
  ledInit();
#endif
#if defined(USB_CHARGER)
  usbChargerInit();
#endif
  __enable_irq();

#if !defined(BOOT)
  hardwareOptions.pcbrev = crsfGetHWID() & 0x0F;
#endif

#if defined(RTCLOCK)
  rtcInit();
#endif

  if (!isDisableBoardOff() && !WAS_RESET_BY_WATCHDOG()) {
    skipCharging = true;
    if (WAS_RESET_BY_SOFTWARE()) {
      LL_RCC_ClearResetFlags();
    }
  }

#if defined(HAPTIC)
  hapticInit();
#endif

  if (!UNEXPECTED_SHUTDOWN())
    sdInit();

  if (skipCharging) {
    runPwrOffCharging();
  }

#if !defined(BOOT)
  crossfireTasksStart();
#endif
}

void boardOff()
{
#if defined(AUDIO_MUTE_GPIO)
  // Mute the amplifier before cutting power so we don't pop the speaker.
  gpio_set(AUDIO_MUTE_GPIO);
#endif

#if !defined(BOOT)
  crossfirePowerOff();
  crossfireTasksStop();
#endif

#if defined(HAPTIC)
  hapticOff();
#endif

  BACKLIGHT_DISABLE();

  while (pwrPressed()) {
    watchdogReset();
  }

  pwrOff();
}

uint16_t getBatteryVoltage()
{
  uint16_t instant_vbat = getAnalogValue(TX_VOLTAGE);
  float batt_scale = TBS_BATT_SCALE;

#if defined(RADIO_TANGO)
  if (hardwareOptions.pcbrev == PCBREV_Tango2_V1)
    batt_scale = TBS_BATT_SCALE;
  else
    batt_scale = TBS_BATT_SCALE2;
#endif

#if !defined(BOOT)
  return (uint16_t)(instant_vbat / batt_scale + g_eeGeneral.txVoltageCalibration);
#else
  return (uint16_t)(instant_vbat / batt_scale);
#endif
}

// anaIn is provided by hal/adc_driver.cpp.

void boardReboot2bootloader(uint32_t isNeedFlash, uint32_t HwId, uint32_t sn)
{
  usbStop();
#if !defined(BOOT)
  crossfirePowerOff();
  
  if (crossfireTaskId._rtos_handle) {
    xSemaphoreGive(get_task_sem(XF_TASK_SEM));
    vTaskDelay(pdMS_TO_TICKS(10));
  }
#endif

  SET_POWER_REASON(SOFTRESET_REQUEST);
  NVIC_SystemReset();
}

void loadDefaultRadioSettings()
{
#if !defined(BOOT)
  g_eeGeneral.backlightMode = e_backlight_mode_keys;
#endif
}

// onUSBConnectMenu is provided by main.cpp.

#if !defined(BOOT)
// xSemaphoreTake / xSemaphoreGive are FreeRTOS macros, not functions, so their
// addresses cannot be taken directly. The TBS CRSF blob (loaded at a fixed
// address, see CROSSFIRE_TASK_ADDRESS in board.h) calls back into EdgeTX
// through the trampoline[] table, so we expose real function pointers here.
// This thin wrapper is the ABI contract with the blob — do not change without
// updating the blob side. When the blob is replaced by native CRSF (Phase 5 in
// PORTING-PLAN.md), this whole trampoline goes away.
static BaseType_t tbs_trampoline_sem_take(SemaphoreHandle_t sem, TickType_t ticksToWait)
{
  return xSemaphoreTake(sem, ticksToWait);
}

static BaseType_t tbs_trampoline_sem_give(SemaphoreHandle_t sem)
{
  return xSemaphoreGive(sem);
}
#endif

void trampolineInit()
{
#if !defined(BOOT)
  trampoline[RTOS_WAIT_SEM_TRAMPOILINE] = (uint32_t)(&tbs_trampoline_sem_take);
  trampoline[RTOS_CLEAR_SEM_TRAMPOILINE] = (uint32_t)(&tbs_trampoline_sem_give);
#endif
}

#if !defined(BOOT)
// Called once from crossfireTasksStart() BEFORE the blob is spawned.
// Must:
//   (1) zero the entire CrossfireSharedData struct (SRAM at
//       SHARED_MEMORY_ADDRESS = 0x10000000 holds garbage at reset);
//   (2) publish the local trampoline[] array so the blob can call
//       xSemaphoreTake/Give/etc. through it;
//   (3) populate rtosApiVersion so the blob refuses to run if the ABI
//       moved.
// io/crsf/crossfire.cpp's crsfInit() does this in the blob-inclusive
// build; until Phase C.3 lands it here, we provide our own initialiser.
void tbsCrsfSharedDataInit()
{
  memset(&crossfireSharedData, 0, sizeof(CrossfireSharedData));

  trampolineInit();
  crossfireSharedData.trampoline = trampoline;
  crossfireSharedData.rtosApiVersion = RTOS_API_VERSION;
}
#endif

// Telemetry EXTI wake-up — INTERRUPT_EXTI_LINE = LL_EXTI_LINE_9 (hal.h),
// which is handled by EXTI9_5_IRQHandler on the F4 vector table, NOT
// EXTI15_10. The previous function name silently did nothing. Once the
// rotary encoder driver is enabled it uses USE_EXTI9_5_IRQ to register
// itself through stm32_exti_driver, so we must NOT hard-define the
// vector here — go through stm32_exti_enable() in the telemetry init
// path (telemetry_driver.cpp, Phase B). This function intentionally
// removed; keeping a #if 0 reference for PORT history.
#if 0  // TODO(port Phase B): wire telemetry EXTI via stm32_exti_enable()
static void telemetry_exti_isr()
{
#if !defined(BOOT)
  BaseType_t xHigherPriorityTaskWoken = pdFALSE;
  xSemaphoreGiveFromISR(get_task_sem(XF_TASK_SEM), &xHigherPriorityTaskWoken);
  portYIELD_FROM_ISR(xHigherPriorityTaskWoken);
#endif
}
#endif

// TIM13 shares the NVIC slot TIM8_UP_TIM13_IRQn on STM32F4 — the vector
// table in targets/common/arm/stm32/f4/vectors_stm32f407xx.c assigns it
// to TIM8_UP_TIM13_IRQHandler (weak default). The TBS-specific
// INTERRUPT_TIM13_IRQHandler symbol in previous revisions was never
// installed in the table, so TIM13 fires silently hit the weak stub.
// Map hal.h's INTERRUPT_NOT_IRQHandler macro (= TIM8_UP_TIM13_IRQHandler)
// to our actual handler.
extern "C" void INTERRUPT_NOT_IRQHandler()
{
#if !defined(BOOT)
  if (LL_TIM_IsActiveFlag_UPDATE(INTERRUPT_NOT_TIMER)) {
    LL_TIM_ClearFlag_UPDATE(INTERRUPT_NOT_TIMER);
    BaseType_t xHigherPriorityTaskWoken = pdFALSE;
    xSemaphoreGiveFromISR(get_task_sem(XF_TASK_SEM), &xHigherPriorityTaskWoken);
    portYIELD_FROM_ISR(xHigherPriorityTaskWoken);
  }
#endif
}

// Bootloader stubs
#if defined(BOOT)
#include "bootloader/boot.h"
void bootloaderInitScreen() {}
void bootloaderDrawScreen(BootloaderState, int, const char*) {}
void bootloaderDrawFilename(const char*, uint8_t, bool) {}
uint32_t bootloaderGetMenuItemCount(int) { return 0; }
bool bootloaderRadioMenu(uint32_t, event_t) { return false; }
bool isFirmwareStart(const uint8_t*) { return true; }
void flashWrite(uint32_t*, const uint32_t*) {}
void blExit() {}

// Minimal stubs for generic bootloader (real drivers pulled in for firmware)
void rotaryEncoderInit() {}
int usbPlugged() { return 0; }
// rotaryEncoderGetValue — bootloader build doesn't pull the common rotary
// encoder driver, provide a zero stub only here.
uint32_t rotaryEncoderGetValue() { return 0; }
#endif
